In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets

digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target==9] = 1
y[digits.target!=9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

/Users/kidand/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [5]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]])

In [7]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [8]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

### 决策函数

In [9]:
log_reg.decision_function(X_test)

array([-22.05700185, -33.02943631, -16.21335414, -80.37912074,
       -48.25121102, -24.54004847, -44.39161228, -25.0429358 ,
        -0.97827574, -19.71740779, -66.25134827, -51.09604113,
       -31.49349749, -46.05331143, -38.67881302, -29.80469525,
       -37.58852711, -82.57572539, -37.81897652, -11.01168447,
        -9.17437139, -85.1300544 , -16.71619123, -46.23732743,
        -5.32994726, -47.91758157, -11.66728036, -39.19605179,
       -25.25292889, -14.3664773 , -16.99782671, -28.91904657,
       -34.33940703, -29.47606116,  -7.85814016,  -3.82091979,
       -24.08167826, -22.16360621, -33.61225968, -23.14026355,
       -26.91804736, -62.38939387, -38.85696034, -66.77263195,
       -20.14487554, -17.47887105, -18.06800777, -22.22224632,
       -29.62301491, -19.73169331,   1.49550696,   8.32079223,
       -36.29312173, -42.50734809, -25.9045751 , -34.98959067,
        -8.42011892, -50.04720364, -51.48209621,  19.88960689,
        -8.91890613, -31.99345356, -11.66102458,  -0.47

In [10]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
decision_scores = log_reg.decision_function(X_test)

In [12]:
np.min(decision_scores)

-85.68612416749173

In [13]:
np.max(decision_scores)

19.889606885682948

In [15]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [17]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]])

In [18]:
precision_score(y_test, y_predict_2)

0.96

In [19]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [20]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [21]:
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]])

In [22]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [23]:
recall_score(y_test, y_predict_3)

0.8888888888888888