In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [6]:
X = iris.data
y = iris.target

In [7]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

### train_test_split

In [9]:
shuffle_indexes = np.random.permutation(len(X))

In [10]:
shuffle_indexes

array([ 32, 124,  56,  26, 103,  73,  54,   2, 139, 137, 117,  72, 120,
        85,  94, 102,  87,  42,  39,  19,  35,  23,  69,   3,  64, 149,
        53,   0, 131, 110,  51,  86, 119,  93,  38, 127,   6,  55,  95,
        67, 114,  97,   8,  47, 122,  34, 143,  91,  45, 135, 101, 133,
        12, 132,  62,  61,   4,  18,  90,  52,  78,   5,  43,  74,  33,
       100,  99,  25, 147, 113,  83, 134, 144,  88, 146,  14,  89,  84,
        46,  60,  41,  79, 118,  37,  76, 121,  15, 148, 105, 109,   1,
        59,  31,  16,  48, 104, 145, 116,  24, 112,  36, 130,  63, 129,
        75, 107,  44,  30,  49,  11,  92,  70,  21,  68, 140, 128,  77,
       115, 142,  65,  71, 106, 136,  13,  20, 126,  58,  66,  40, 125,
        96, 123,  28, 138,  17,  29,  57, 108,  81,  82,  22,  10,  80,
        27,  50,   9, 111,   7,  98, 141])

In [11]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [12]:
test_size

30

In [13]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [14]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 使用自己的算法

In [17]:
from playML.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [19]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [20]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [22]:
from playML.kNN import KNNClassifier

In [23]:
my_knn_clf = KNNClassifier(k=3)

In [24]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [25]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([0, 1, 1, 2, 2, 0, 2, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 2, 0, 1,
       0, 0, 0, 2, 2, 1, 1, 1])

In [26]:
y_test

array([0, 1, 1, 2, 2, 0, 1, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 2, 0, 1,
       0, 0, 0, 2, 1, 1, 1, 1])

In [27]:
sum(y_predict == y_test)

28

In [28]:
# 预测准确率
sum(y_predict == y_test)/len(y_test)

0.9333333333333333

### sklearn中的train_test_split

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
# test_size 默认为 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [31]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [32]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
