In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target)

### scikit-learn中的StandardScaler

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
standardScaler = StandardScaler()

In [11]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
standardScaler.mean_

array([5.83303571, 3.09017857, 3.67410714, 1.16964286])

In [15]:
standardScaler.scale_

array([0.80516063, 0.42572623, 1.78319264, 0.77688013])

In [16]:
standardScaler.transform(X_train)

array([[-1.77981344,  0.25796256, -1.33138007, -1.24812416],
       [-0.04102997, -1.15139386,  0.18275808,  0.03907571],
       [ 0.57996413,  0.4928553 ,  0.57531241,  0.55395566],
       [-0.78622289,  0.96264077, -1.21922169, -1.24812416],
       [-0.53782525,  0.72774803, -1.21922169, -0.99068419],
       [-1.5314158 ,  0.25796256, -1.27530088, -1.24812416],
       [ 1.69775351,  0.25796256,  1.30434189,  0.81139564],
       [ 0.95256059, -0.21182291,  0.40707484,  0.29651569],
       [ 1.82195233, -0.44671565,  1.47257946,  0.81139564],
       [-0.78622289,  0.72774803, -1.27530088, -1.24812416],
       [ 0.70416295,  0.25796256,  0.91178756,  1.45499557],
       [ 1.32515705,  0.25796256,  1.13610432,  1.45499557],
       [ 1.07675941, -0.21182291,  0.85570836,  1.45499557],
       [-1.03462052, -2.56075028, -0.09763788, -0.21836426],
       [ 0.45576531,  0.72774803,  0.96786675,  1.45499557],
       [ 0.57996413, -1.3862866 ,  0.68747079,  0.42523567],
       [-1.03462052,  0.

In [17]:
X_train

array([[4.4, 3.2, 1.3, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [6.3, 3.3, 4.7, 1.6],
       [5.2, 3.5, 1.5, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [4.6, 3.2, 1.4, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.3, 2.9, 6.3, 1.8],
       [5.2, 3.4, 1.4, 0.2],
       [6.4, 3.2, 5.3, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [6.7, 3. , 5.2, 2.3],
       [5. , 2. , 3.5, 1. ],
       [6.2, 3.4, 5.4, 2.3],
       [6.3, 2.5, 4.9, 1.5],
       [5. , 3.5, 1.3, 0.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.2, 4. , 1. ],
       [7. , 3.2, 4.7, 1.4],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 2.7, 5.3, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.7, 3.1, 4.4, 1.4],
       [5. , 3.4, 1.6, 0.4],
       [4.9, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [6.3, 2.3, 4.4, 1.3],
       [5. , 3. , 1.6, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 2.5, 3. , 1.1],
       [6.5, 3. , 5.2, 2. ],
       [4.9, 3

In [18]:
X_train = standardScaler.transform(X_train)

In [19]:
X_train

array([[-1.77981344,  0.25796256, -1.33138007, -1.24812416],
       [-0.04102997, -1.15139386,  0.18275808,  0.03907571],
       [ 0.57996413,  0.4928553 ,  0.57531241,  0.55395566],
       [-0.78622289,  0.96264077, -1.21922169, -1.24812416],
       [-0.53782525,  0.72774803, -1.21922169, -0.99068419],
       [-1.5314158 ,  0.25796256, -1.27530088, -1.24812416],
       [ 1.69775351,  0.25796256,  1.30434189,  0.81139564],
       [ 0.95256059, -0.21182291,  0.40707484,  0.29651569],
       [ 1.82195233, -0.44671565,  1.47257946,  0.81139564],
       [-0.78622289,  0.72774803, -1.27530088, -1.24812416],
       [ 0.70416295,  0.25796256,  0.91178756,  1.45499557],
       [ 1.32515705,  0.25796256,  1.13610432,  1.45499557],
       [ 1.07675941, -0.21182291,  0.85570836,  1.45499557],
       [-1.03462052, -2.56075028, -0.09763788, -0.21836426],
       [ 0.45576531,  0.72774803,  0.96786675,  1.45499557],
       [ 0.57996413, -1.3862866 ,  0.68747079,  0.42523567],
       [-1.03462052,  0.

In [21]:
X_test_standard = standardScaler.transform(X_test)
X_test_standard

array([[ 2.19454879, -0.21182291,  1.64081703,  1.1975556 ],
       [-1.90401226, -0.21182291, -1.44353845, -1.37684415],
       [-1.65561462, -1.85607207, -1.33138007, -1.11940418],
       [-1.40721698,  0.25796256, -1.1631425 , -1.24812416],
       [-0.41362643,  2.60688993, -1.27530088, -1.24812416],
       [ 0.82836177, -0.68160839,  0.51923322,  0.42523567],
       [ 0.45576531, -0.44671565,  0.35099565,  0.1677957 ],
       [ 1.94615115, -0.68160839,  1.36042108,  0.94011562],
       [-0.53782525, -0.21182291,  0.46315403,  0.42523567],
       [-1.15881934, -1.3862866 ,  0.46315403,  0.68267565],
       [ 0.08316885,  0.25796256,  0.6313916 ,  0.81139564],
       [-0.16522879, -0.68160839,  0.23883727,  0.1677957 ],
       [-0.04102997, -0.91650113,  0.79962917,  0.94011562],
       [ 1.07675941, -1.3862866 ,  1.19218351,  0.81139564],
       [ 0.33156649, -0.21182291,  0.68747079,  0.81139564],
       [ 2.31874761,  1.66731898,  1.69689622,  1.32627558],
       [ 1.32515705,  0.

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [24]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [25]:
knn_clf.score(X_test_standard, y_test)

0.9210526315789473

In [26]:
knn_clf.score(X_test, y_test)

0.34210526315789475