In [1]:
import numpy as np

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [10]:
# 判断维度
x.ndim

1

In [11]:
X.ndim

2

In [14]:
# 判断数组形状
x.shape

(10,)

In [15]:
X.shape

(3, 5)

In [18]:
# 元素个数
x.size

10

In [19]:
X.size

15

### numpy.array 的数据访问

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[0]

0

In [22]:
x[-1]

9

In [23]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
# 不推荐
X[0][0]

0

In [25]:
# 推荐
X[(0, 0)]

0

In [26]:
X[(2, 2)]

12

In [28]:
# 推荐
X[2, 2]

12

In [29]:
x[0:5]

array([0, 1, 2, 3, 4])

In [30]:
x[:5]

array([0, 1, 2, 3, 4])

In [31]:
x[5:]

array([5, 6, 7, 8, 9])

In [32]:
# 第三个参数为步长
x[::2]

array([0, 2, 4, 6, 8])

In [33]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [36]:
# 此处有坑
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [38]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [40]:
# 降维
X[0]

array([0, 1, 2, 3, 4])

In [41]:
X[0, :]

array([0, 1, 2, 3, 4])

In [42]:
X[:, 0]

array([ 0,  5, 10])

In [44]:
X[:, 0].ndim

1

In [46]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [47]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [49]:
# numpy取子矩阵用的引用，修改子矩阵对原矩阵有影响
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [51]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
# copy()方法可解决前一个问题
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [55]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [56]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [57]:
x.shape

(10,)

In [58]:
x.ndim

1

In [59]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
B = x.reshape(1, 10)
# 此时的B变为二维数组
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
B.ndim

2

In [67]:
B.shape

(1, 10)

In [69]:
# 只考虑行数时，列数传-1
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [70]:
# 只考虑列数时，行数传-1
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 合并操作

In [77]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [75]:
x

array([1, 2, 3])

In [78]:
y

array([3, 2, 1])

In [79]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [80]:
z = np.array([666, 666, 666])

In [81]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [82]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
# axis=1 表示沿着列进行拼接（默认为0）
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [87]:
# 二维拼一维
# 方法1
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [88]:
# 方法2
# vstack()垂直方向拼接
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [89]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [90]:
# hstack()水平方向拼接
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [91]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
x1, x2, x3 = np.split(x, [3, 7])

In [93]:
x1

array([0, 1, 2])

In [94]:
x2

array([3, 4, 5, 6])

In [95]:
x3

array([7, 8, 9])

In [96]:
x1, x2 = np.split(x, [5])

In [97]:
x1

array([0, 1, 2, 3, 4])

In [98]:
x2

array([5, 6, 7, 8, 9])

In [99]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
A1, A2 = np.split(A, [2])

In [101]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [102]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
A1, A2 = np.split(A, [2], axis=1)

In [104]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [105]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [106]:
# 垂直方向分割
upper, lower = np.vsplit(A, [2])

In [107]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [108]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
# 水平方向进行分割
left, right = np.hsplit(A, [2])

In [110]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [111]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [112]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
x, y = np.hsplit(data, [-1])

In [114]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [115]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [116]:
# 转为向量
y[:, 0]

array([ 3,  7, 11, 15])