### 聚合操作

In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.28599616, 0.60597988, 0.90342102, 0.18118448, 0.64349044,
       0.89610664, 0.7076155 , 0.82410898, 0.52337108, 0.24731129,
       0.96032286, 0.00930018, 0.42013387, 0.9736316 , 0.68714476,
       0.3166428 , 0.92396507, 0.90040275, 0.2488667 , 0.30084483,
       0.6362829 , 0.11083272, 0.46208996, 0.27230923, 0.31787561,
       0.14174263, 0.53479232, 0.39714496, 0.839714  , 0.30199043,
       0.55385647, 0.03319595, 0.56352658, 0.85314892, 0.78071453,
       0.94374137, 0.77454738, 0.79388696, 0.05823096, 0.34500114,
       0.76846802, 0.4743473 , 0.32157307, 0.32347156, 0.59046398,
       0.34681249, 0.44852207, 0.77608394, 0.99880495, 0.53721113,
       0.03074373, 0.01841329, 0.74203068, 0.86200828, 0.54281678,
       0.42143597, 0.21817981, 0.99754295, 0.18919938, 0.2663612 ,
       0.62774837, 0.55931751, 0.50343228, 0.68655424, 0.28351329,
       0.21664887, 0.66828604, 0.40772076, 0.36584965, 0.77909728,
       0.73350314, 0.07563725, 0.4947493 , 0.31302464, 0.50071

In [3]:
sum(L)

48.27183154916658

In [4]:
np.sum(L)

48.27183154916658

In [5]:
# 两个sum的效率区别
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

134 ms ± 3.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
375 µs ± 30.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

1.203792522108671e-06

In [7]:
np.max(big_array)

0.999999399152454

In [8]:
big_array.min()

1.203792522108671e-06

In [9]:
big_array.max()

0.999999399152454

In [10]:
big_array.sum()

499694.5723327936

> 用`np.方法`更全一些，推荐

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
# 每一列的和
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
# 每一行的和
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
# 所有元素相乘
np.prod(X)

0

In [16]:
np.prod(X + 1)

20922789888000

In [17]:
# 求平均值
np.mean(X)

7.5

In [18]:
# 求中位数
np.median(X)

7.5

In [19]:
# 百分位 q=50时是中位数，q=100时是最大值
np.percentile(big_array, q=50)

0.4994537950391212

In [20]:
np.median(big_array)

0.4994537950391212

In [21]:
np.percentile(big_array, q=100)

0.999999399152454

In [22]:
np.max(big_array)

0.999999399152454

In [24]:
# 打印常用的五个百分位
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.203792522108671e-06
0.2502185252590863
0.4994537950391212
0.7493633652362869
0.999999399152454


In [25]:
# 求方差
np.var(big_array)

0.08315203805924173

In [26]:
# 求标准差
np.std(big_array)

0.2883609509958686

In [27]:
x = np.random.normal(0, 1, 1000000)
np.mean(x)

0.0012879448904828906

In [28]:
np.std(x)

1.0002329867428368

### 索引

In [30]:
np.min(x)

-4.652398303746586

In [31]:
# 获得最小值索引
np.argmin(x)

20660

In [32]:
x[20660]

-4.652398303746586

In [33]:
# 获得最大值索引
np.argmax(x)

882093

In [34]:
x[882093]

4.595177860978732

In [35]:
np.max(x)

4.595177860978732

### 排序和使用索引

In [62]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
# 打乱顺序
np.random.shuffle(x)
x

array([ 7,  4,  1,  9, 15,  3,  8,  6, 11, 13, 10, 12,  5,  0,  2, 14])

In [64]:
# 排序（不影响x）
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
x

array([ 7,  4,  1,  9, 15,  3,  8,  6, 11, 13, 10, 12,  5,  0,  2, 14])

In [66]:
# 排序（影响x）
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
X = np.random.randint(10, size=(4, 4))
X

array([[3, 1, 9, 9],
       [1, 8, 7, 0],
       [4, 0, 1, 9],
       [6, 1, 1, 2]])

In [68]:
np.sort(X)

array([[1, 3, 9, 9],
       [0, 1, 7, 8],
       [0, 1, 4, 9],
       [1, 1, 2, 6]])

In [69]:
# sort()中,axis的默认值是1
np.sort(X, axis=1)

array([[1, 3, 9, 9],
       [0, 1, 7, 8],
       [0, 1, 4, 9],
       [1, 1, 2, 6]])

In [70]:
np.sort(X, axis=0)

array([[1, 0, 1, 0],
       [3, 1, 1, 2],
       [4, 1, 7, 9],
       [6, 8, 9, 9]])

In [71]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
np.random.shuffle(x)
x

array([ 3,  1,  0,  7,  2, 10, 13,  5, 12,  8, 14,  6,  4, 15, 11,  9])

In [74]:
# 得到的是索引的排序
np.argsort(x)

array([ 2,  1,  4,  0, 12,  7, 11,  3,  9, 15,  5, 14,  8,  6, 10, 13])

In [76]:
# 快排中的标定点，3前面的比3小，3后面的比3大
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5, 13, 10, 12,  8, 14,  6,  7, 15, 11,  9])

In [77]:
np.argpartition(x, 3)

array([ 2,  1,  4,  0, 12,  7,  6,  5,  8,  9, 10, 11,  3, 13, 14, 15])

In [78]:
X

array([[3, 1, 9, 9],
       [1, 8, 7, 0],
       [4, 0, 1, 9],
       [6, 1, 1, 2]])

In [79]:
np.argsort(X, axis=1)

array([[1, 0, 2, 3],
       [3, 0, 2, 1],
       [1, 2, 0, 3],
       [1, 2, 3, 0]])

In [80]:
np.argsort(X, axis=0)

array([[1, 2, 2, 1],
       [0, 0, 3, 3],
       [2, 3, 1, 0],
       [3, 1, 0, 2]])

In [82]:
np.argpartition(X, 2, axis=1)

array([[1, 0, 2, 3],
       [3, 0, 2, 1],
       [1, 2, 0, 3],
       [1, 2, 3, 0]])

In [83]:
np.argpartition(X, 2, axis=0)

array([[1, 2, 2, 1],
       [0, 0, 3, 3],
       [2, 3, 1, 2],
       [3, 1, 0, 0]])